# -*- coding: utf-8 -*-
"""Library management.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rOWkvl71_aw65_NrnvoCL19oXeG53BtR
"""

#library
library_details={
    'P001':['C programming','Data Structures'],
    'P002':['Python','C programming'],
    'P003':['Operating System'],
    'P004':['C programming','Python'],
    'P005':[],
    'P006':['Data Structures']
}


#Average number of books
total_members=len(library_details)
total_books= sum(len(books) for books in library_details.values())
average=total_books/total_members
print('The average number of books borrowed is',average)


#Books taken and their numbers
all_books=[]
for books in library_details.values():
  all_books.extend(books)

book_count={}
for book in all_books:
  if book in book_count:
    book_count[book] += 1
  else:
    book_count[book] = 1

print (book_count)


#most borrowed
most_borrowed=""
max_count=0
for book in book_count:
  if book_count[book] > max_count:
    max_count=book_count[book]
    most_borrowed= book
print(most_borrowed,"is the most borrowed i.e. taken",max_count,"times")


#least borrowed
least_borrowed= min(book_count,key=book_count.get)
least_count=book_count[least_borrowed]
print(least_borrowed,"is the least borrowed i.e. taken",least_count,"times")